In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("smartphones - smartphones.csv")
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [3]:
df.head(11)

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
5,Samsung Galaxy F23 5G (6GB RAM + 128GB),"₹16,999",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 750G, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 1 TB",Android v12
6,Apple iPhone 14,"₹65,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor","6 GB RAM, 128 GB inbuilt",3279 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
7,Xiaomi Redmi Note 12 Pro Plus,"₹29,999",86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4980 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v12
8,Nothing Phone 1,"₹26,749",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,OnePlus Nord 2T 5G,"₹28,999",84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
10,Realme 10 Pro,"₹18,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.72 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13

In [4]:
df.head(114)

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
109,OnePlus 10R 5G (12GB RAM + 256GB),"₹36,999",87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
110,Tecno Phantom X2,"₹39,999",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
111,Apple iPhone 12,"₹51,999",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
112,Xiaomi Redmi K50i 5G,"₹22,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8100, Octa Core, 2.85 GHz Processor","6 GB RAM, 128 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
113,Samsung Galaxy A53 5G,"₹31,999",87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1280, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12

Here is the **full consolidated content** from all three screenshots you uploaded, formatted cleanly for documentation, reporting, or implementation:

---

## 📊 Data Assessing

### ⚠️ Quality Issues

1. **Model** – Some brands are written differently (e.g., "OPPO" in the `model` column). 'consistency'
2. **Price** – Contains unnecessary **₹** symbols.'validity'
3. **Price** – Contains commas **( , )** between numbers.'validity'
4. **Price** – The phone **Namotel** has an unusually low price of **₹99**.'accuracy'
5. **Ratings** – Contains **missing values**.'completeness'
6. **Processor** – Contains incorrect values for some Samsung phones.'validity'

   * Affected rows:
     `642, 647, 649, 659, 667, 701, 750, 759, 819, 859, 883, 884, 919, 927, 929, 932, 1002`
7. **Model** – An **iPod** is present in row **756**, which is not a smartphone.'validity'
8. **Memory** – Incorrect values in rows:
   `441, 485, 534, 553, 584, 610, 613, 642, 647, 649, 659, 667, 701, 750, 759, 819, 859, 884, 919, 927, 929, 932, 990, 1002`'validity'
9. **Battery** – Incorrect values in rows:
   `113, 151, 309, 365, 378, 441, 450, 553, 584, 610, 613, 630, 642, 647, 649, 659, 667, 701, 750, 756, 759, 764, 819, 855, 859, 884, 915, 916, 927, 929, 932, 990, 1002`'validity'
10. **Display** – Sometimes frequency is not available.'validity'
11. **Display** – Incorrect values in rows:
    `378, 441, 450, 553, 584, 610, 613, 630, 642, 647, 649, 659, 667, 701, 750, 759, 764, 819, 859, 884, 915, 916, 927, 929, 932, 990, 1002`'validity'
12. **Foldable Phones** – Some phones are foldable and this information is scattered.'validity'
13. **Camera** – Terms like **Dual**, **Triple**, and **Quad** are used to represent camera count; front and rear cameras are separated by **"&"**.
14. **Camera** – Problematic rows:
    `100, 113, 151, 157, 161, 238, 273, 308, 309, 323, 324, 365, 367, 378, 394, 441, 450, 484, 506, 534, 553, 571, 572, 575, 584, 610, 613, 615, 630, 642, 647, 649, 659, 667, 684, 687, 705, 711, 723, 728, 750, 756, 759, 764, 792, 819, 846, 854, 855, 858, 883, 884, 896, 915, 916, 927, 929, 932, 945, 956, 990, 995, 1002, 1016`'validity'
15. **Card** – Sometimes contains info about **OS** and **camera**.'validity'
16. **OS** – Sometimes contains info about **Bluetooth** and **FM Radio**.'validity'
17. **OS** – Issue with rows: `324, 378`
18. **OS** – Sometimes contains OS version names like **Lollipop**.'consistency'
19. Missing values in camara, card, and os.'completeness'
20.Dataype of price and reating is incorrect.'validity'

---

## 🧹 Tidiness Issues

1. **SIM** – Can be split into 3 columns:

   * `has_5g`, `has_NFC`, `has_IR_Blaster`
2. **RAM** – Can be split into 2 columns:

   * `RAM`, `ROM`
3. **Processor** – Can be split into:

   * `processor_name`, `cores`, `cpu_speed`
4. **Battery** – Can be split into:

   * `battery_capacity`, `fast_charging_available`
5. **Display** – Can be split into:

   * `size`, `resolution_width`, `resolution_height`, `frequency`
6. **Camera** – Can be split into:

   * `front_camera`, `rear_camera`
7. **Card** – Can be split into:

   * `supported`, `extended_upto`

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [6]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [7]:
#Check duplicated values
df.duplicated().sum()

np.int64(0)

In [8]:
#make a copy data df1 name
df1 = df.copy()

In [9]:
df1

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,"₹34,990",83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,"₹14,990",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),"₹28,990",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,"₹19,990",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,"₹24,990",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [10]:
#change ₹ sine nothing ('') then we replace all the , nothing('') 
df1['price']=df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [11]:
df1

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [12]:
#Reset index reset index value +2 bz our csv data start with 2.
df1=df1.reset_index()
df1['index']=df1['index']+2

In [13]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [14]:
processor_rows=set((642, 647, 649, 659, 667, 701, 750, 759, 819, 859, 883, 884, 919, 927, 929, 932, 1002))
ram_rows=set((441, 485, 534, 553, 584, 610, 613, 642, 647, 649, 659, 667, 701, 750, 759, 819, 859, 884, 919, 927, 929, 932, 990, 1002))
battry_rows=set((113, 151, 309, 365, 378, 441, 450, 553, 584, 610, 613, 630, 642, 647, 649, 659, 667, 701, 750, 756, 759, 764, 819, 855, 859, 884, 915, 916, 927, 929, 932, 990, 1002))
display_rows=set((378, 441, 450, 553, 584, 610, 613, 630, 642, 647, 649, 659, 667, 701, 750, 759, 764, 819, 859, 884, 915, 916, 927, 929, 932, 990, 1002))
camera_rows=set((100, 113, 151, 157, 161, 238, 273, 308, 309, 323, 324, 365, 367, 378, 394, 441, 450, 484, 506, 534, 553, 571, 572, 575, 584, 610, 613, 615, 630, 642, 647, 649, 659, 667, 684, 687, 705, 711, 723, 728, 750, 756, 759, 764, 792, 819, 846, 854, 855, 858, 883, 884, 896, 915, 916, 927, 929, 932, 945, 956, 990, 995, 1002, 1016))

In [15]:
#This 68 rows atleat one columns probelm
df1[df1['index'].isin(processor_rows|ram_rows|battry_rows|display_rows|camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
988,990,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [16]:

##This the data all the Four columns problem
df1[df1['index'].isin(processor_rows&ram_rows&battry_rows&display_rows&camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
640,642,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,649,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,659,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,667,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
748,750,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
757,759,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
817,819,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,929,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,932,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [17]:
df1[df1['index'].isin(processor_rows&ram_rows&battry_rows&display_rows&camera_rows)]['price'].mean()

np.float64(2537.6923076923076)

In [18]:
#All this phone whose price is greater then 3400 all are smartphone by observing our data
df1=df1[df1['price']>=3400]

In [19]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [20]:
df1[df1['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [21]:
df1[df1['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [22]:
len(processor_rows)

17

In [23]:
df1.drop([645,857,882,925],inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_12408\1676279141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([645,857,882,925],inplace=True)

In [24]:
df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [25]:
df1.drop(582,inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_12408\544825702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(582,inplace=True)

In [26]:


df1[df1['index'].isin(battry_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [27]:
df1.drop([376,754],inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_12408\2579486625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([376,754],inplace=True)

In [28]:
temp_df=df1[df1['index'].isin(battry_rows)]

In [29]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [30]:
temp_df.iloc[:,7:]

,battery,display,camera,card,os
111,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [31]:
x=temp_df.iloc[:,7:].shift(1,axis=1).values

In [32]:
x

array([[None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '4.7 inches, 750\u2009x\u20091334\u2009px Display',
        '12\u2009MP Rear & 7\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [None,
        '6.06 inches, 1170\u2009x\u20092532\u2009px, 120 Hz Display with Punch Hole',
        '50\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [None, '6.1 inches, 750\u2009x\u20091580\u2009px Display',
        '12\u2009MP Rear & 10.8\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v16'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14']], dtype=object)

In [33]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [34]:
x_index=temp_df.index

In [35]:
df1.loc[temp_df.index,temp_df.columns[7:]].shape

(11, 5)

In [36]:
df1.loc[temp_df.index,temp_df.columns[7:]]=x

In [37]:
x.shape

(11, 5)

In [38]:
df1[df1['index'].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [39]:
df1[df1['index'].isin(display_rows)].shape

(6, 12)

In [40]:
len(display_rows)

27

# camera_rows

In [41]:
df1[df1['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [42]:
df1[df1['index'].isin(camera_rows)].shape

(39, 12)

In [43]:
len(camera_rows)

64

In [44]:
df1.drop([155,271],inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_12408\1298457551.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([155,271],inplace=True)

In [45]:
df1[df1['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [46]:
temp_df=df1[df1['index'].isin(camera_rows)]

In [47]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [48]:
#this is those phone where problem
temp_df[temp_df['camera'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [49]:

temp_df[temp_df['camera'].str.contains('MP')].shape

(12, 12)

In [50]:
#This is those phone where not problem
temp_df[~temp_df['camera'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [51]:
temp_df[~temp_df['camera'].str.contains('MP')].shape

(25, 12)

In [52]:
temp_df=temp_df[~temp_df['camera'].str.contains('MP')]

In [53]:
df1.loc[temp_df.index,'camera']=temp_df['card'].values

In [54]:
df1[df1['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [55]:
df1['camera'].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                  34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                            23
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                   20
                                                                      ..
64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 MP Dual Front Camera     1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP Front Camera                 1
50 MP + 50 MP + 50 MP Triple Rear & 12 MP Front Camera                 1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                 1
48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP Front Camera            1
Name: count, Length: 285, dtype: int64

In [56]:
#Check the all value count
#pd.set_option('display.max_rows',None)

In [57]:
df1['camera'].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                  34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                            23
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                   20
                                                                      ..
64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 MP Dual Front Camera     1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP Front Camera                 1
50 MP + 50 MP + 50 MP Triple Rear & 12 MP Front Camera                 1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                 1
48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP Front Camera            1
Name: count, Length: 285, dtype: int64

# Card columns

In [58]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              123
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         91
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Memory Card (Hybrid), upto 512 GB                                       11
Android v10                                                             11
Memory Card Supported, upto 128 GB                                       6
Memory Card Supported, upto 2 TB                                         5
Memory Card Supported, upto 32 GB                                        4
Memory Card (Hybrid), upto 64 GB                                         3
Memory Card (Hybrid), upto 128 GB                                        3
50 MP Quad Rear & 16 MP Front Camera                                     2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
Android v9.0 (Pie)                                                       2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                    1
Android v12.1                                                            1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                        1
Memory Card Supported, upto 1000 GB                                      1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                   1
iOS v10                                                                  1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                     1
Android v10.0                                                            1
iOS v13                                                                  1
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                  1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                   1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                  1
HarmonyOS v2.0                                                           1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
5 MP Rear & 2 MP Front Camera                                            1
Memory Card (Hybrid), upto 2 TB                                          1
HarmonyOS                                                                1
48 MP Quad Rear Camera                                                   1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                   1
Name: count, dtype: int64

In [59]:
#Replace the card column where 'MP' is found replace it Memory Card Not Supported 
temp_df=df1[df1['card'].str.contains('MP')]

In [60]:
df1.loc[temp_df.index,'card']='Memory Card Not Supported'

In [61]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              149
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [62]:
#Find that values in card columns where Android words present
df1[df1['card'].str.contains('Android')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,1011,Xiaomi Civi 3,32990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 ...,Android v13,No FM Radio
1011,1013,Oppo Find X6,69990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP Fron...,Android v12,No FM Radio
1012,1014,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio
1013,1015,Google Pixel 8 Pro,70990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor 3, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.73 inches, 1440 x 3120 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio

In [63]:
df1[df1['card'].str.contains('Android')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,1011,Xiaomi Civi 3,32990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 ...,Android v13,No FM Radio
1011,1013,Oppo Find X6,69990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP Fron...,Android v12,No FM Radio
1012,1014,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio
1013,1015,Google Pixel 8 Pro,70990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor 3, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.73 inches, 1440 x 3120 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio

In [64]:
pd.set_option('display.max_rows',None)

In [65]:
temp_df=df1[~df1['card'].str.contains('Memory Card')]

In [66]:
df1.loc[temp_df.index,'card']='Memory Card Not Supported'

In [67]:
df1['card'].value_counts()

card
Memory Card Not Supported              362
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [72]:
df1['os'].value_counts()

os
Android v12                           287
Android v11                           233
No FM Radio                           180
Android v10                            58
Android v13                            45
Bluetooth                              34
Android v9.0 (Pie)                     27
Android v10.0                          22
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
iOS v14                                 6
Memory Card Not Supported               6
Android v11.0                           4
Android v8.0 (Oreo)                     4
iOS v13                                 3
iOS v15.0                               3
Android v5.1.1 (Lollipop)               2
iOS v14.0                               2
Memory Card (Hybrid), upto 256 GB       2
EMUI v12                                2
Android v6.0 (Marshmallow)              2
Memory Card (Hybrid), upto 2 TB         2
Harmony v2.0                            2
Memory Card Supported, upto 256 GB      2
HarmonyOS v2                            1
Hongmeng OS v3.0                        1
Android v5.1 (Lollipop)                 1
Android v4.4.2 (KitKat)                 1
iOS v17                                 1
Android v12.1                           1
iOS v12.3                               1
iOS v13.0                               1
Memory Card (Hybrid)                    1
Hongmeng OS v4.0                        1
RTOS (Series 30+)                       1
Pragati OS (Powered by Android)         1
HarmonyOS v2.0                          1
Memory Card Supported, upto 128 GB      1
Android v7.1 (Nougat)                   1
Android                                 1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [69]:
df1[df1['os'].str.contains('Memory Card')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,Memory Card Not Supported,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"

In [71]:
pd.set_option('display.max_rows',None)

In [73]:
temp_df=df1[df1['os']=='Biuethooth']

In [75]:
df1.shape

(982, 12)

***Chaking all the columns values are same or not***

In [76]:
df1['sim'].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               317
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                54
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, Wi-Fi                                        7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [77]:
df1['processor'].value_counts()

processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor         29
Helio P35, Octa Core, 2.3 GHz Processor                27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor       26
Snapdragon 695, Octa Core, 2.2 GHz Processor           23
Snapdragon 680, Octa Core, 2.4 GHz Processor           23
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor        23
Helio G35, Octa Core, 2.3 GHz Processor                20
Snapdragon  680, Octa Core, 2.4 GHz Processor          18
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor         18
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor          17
Bionic A15, Hexa Core, 3.22 GHz Processor              16
Snapdragon  695, Octa Core, 2.2 GHz Processor          16
Dimensity  810 5G, Octa Core, 2.4 GHz Processor        15
Snapdragon 870, Octa Core, 3.2 GHz Processor           15
Helio G99, Octa Core, 2.2 GHz Processor                14
Helio G80, Octa Core, 2 GHz Processor                  14
Snapdragon 778G, Octa Core, 2.4 GHz Processor          12
Dimensity 1080, Octa Core, 2.6 GHz Processor           12
Dimensity 810 5G, Octa Core, 2.4 GHz Processor         12
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor      12
Helio G96, Octa Core, 2.05 GHz Processor               12
Dimensity  920 5G, Octa Core, 2.5 GHz Processor        11
Snapdragon 888, Octa Core, 2.84 GHz Processor          11
Snapdragon  888 , Octa Core, 2.84 GHz Processor        10
Helio G25, Octa Core, 2 GHz Processor                  10
Helio A22, Quad Core, 2 GHz Processor                  10
Helio  G85, Octa Core, 2 GHz Processor                 10
Tiger T612, Octa Core, 1.82 GHz Processor               9
Helio G37, Octa Core, 2.3 GHz Processor                 9
Octa Core Processor                                     9
Snapdragon 720G, Octa Core, 2.3 GHz Processor           8
Helio G88, Octa Core, 2 GHz Processor                   8
Dimensity 1300, Octa Core, 3 GHz Processor              8
Bionic A14, Hexa Core, 3.1 GHz Processor                8
Snapdragon  870, Octa Core, 3.2 GHz Processor           7
Bionic  A16, Hexa Core Processor                        7
Snapdragon 865, Octa Core, 2.84 GHz Processor           7
Helio G95, Octa Core, 2.05 GHz Processor                7
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor       6
Exynos 850, Octa Core, 2 GHz Processor                  6
Helio G85, Octa Core, 2 GHz Processor                   6
Helio P22, Octa Core, 2 GHz Processor                   6
Helio  G96, Octa Core, 2.05 GHz Processor               6
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor       6
Dimensity  8100, Octa Core, 2.85 GHz Processor          5
Dimensity 8200, Octa Core, 3.1 GHz Processor            5
Exynos  2100, Octa Core, 2.9 GHz Processor              5
Snapdragon  7 Gen1, Octa Core, 2.36 GHz Processor       5
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor      5
Dimensity 1200, Octa Core, 3 GHz Processor              5
Snapdragon  732G, Octa Core, 2.3 GHz Processor          5
Snapdragon  778G, Octa Core, 2.4 GHz Processor          5
A13 Bionic, Hexa Core, 2.65 GHz Processor               5
Unisoc  SC9863A, Octa Core, 1.6 GHz Processor           5
Snapdragon  695 , Octa Core, 2.2 GHz Processor          5
Snapdragon 695 , Octa Core, 2.2 GHz Processor           5
Dimensity 720, Octa Core, 2 GHz Processor               4
Dimensity 800U, Octa Core, 2.4 GHz Processor            4
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor          4
Exynos  1280, Octa Core, 2.4 GHz Processor              4
Snapdragon  480 , Octa Core, 2 GHz Processor            4
Snapdragon  778G , Octa Core, 2.4 GHz Processor         4
Dimensity 900, Octa Core, 2 GHz Processor               4
Exynos 990, Octa Core, 2.73 GHz Processor               4
Dimensity 9000, Octa Core, 3.05 GHz Processor           4
Unisoc  T606, Octa Core, 1.6 GHz Processor              4
Exynos  990, Octa Core, 2.73 GHz Processor              3
Snapdragon  665, Octa Core, 2 GHz Processor             3
 Snapdragon  695, Octa Core, 2.2 GHz Processor          3
Snapdragon  8 Gen2, Octa Core, 3.2 GHz Processor        3
Dimensity  930, Octa Core, 2.2 GHz Processor            3
Snapdragon 845, Octa Core, 2.8 GHz Processor            3
Snapdragon 480+, Octa Core, 2.2 GHz Processor           3
Snapdragon  865 , Octa Core, 2.84 GHz Processor         3
Helio  G99, Octa Core, 2.2 GHz Processor                3
Snapdragon 888+, Octa Core, 2.9 GHz Processor           3
Exynos 1280, Octa Core, 2.4 GHz Processor               3
Snapdragon 765G , Octa Core, 2.4 GHz Processor          3
Snapdragon  888+, Octa Core, 2.9 GHz Processor          3
Tiger  T616, Octa Core, 1.8 GHz Processor               3
Bionic  A16                                             3
Qualcomm 215, Quad Core, 1.3 GHz Processor              3
Dimensity 700, Octa Core, 2.2 GHz Processor             3
Helio  G25, Octa Core, 2 GHz Processor                  3
Helio G95, Octa Core, 2 GHz Processor                   3
Dimensity 8100-Max, Octa Core, 2.85 GHz Processor       3
Quad Core, 1.3 GHz Processor                            3
Dimensity 810, Octa Core, 2.4 GHz Processor             3
Helio G96, Octa Core, 2 GHz Processor                   3
Dimensity  700 5G, Octa Core, 2.2 GHz Processor         3
Octa Core, 2 GHz Processor                              3
Exynos  850, Octa Core, 2 GHz Processor                 3
Snapdragon 765G, Octa Core, 2.4 GHz Processor           3
Dimensity  1300, Octa Core, 3 GHz Processor             3
Exynos 1330, Octa Core, 2.4 GHz Processor               3
Snapdragon  750G, Octa Core, 2.2 GHz Processor          2
Helio G70, Octa Core, 2 GHz Processor                   2
Kirin  990, Octa Core, 2.86 GHz Processor               2
Helio, Octa Core Processor                              2
SC9863A, Octa Core, 1.6 GHz Processor                   2
Snapdragon  480+, Octa Core, 2.2 GHz Processor          2
Dimensity  8200, Octa Core, 3.1 GHz Processor           2
Quad Core, 1.6 GHz Processor                            2
Unisoc SC9863A, Octa Core, 1.6 GHz Processor            2
Dimensity 9200, Octa Core, 3.05 GHz Processor           2
Snapdragon 732G , Octa Core, 2.3 GHz Processor          2
Google  Tensor, Octa Core Processor                     2
Google  Tensor, Octa Core, 2.8 GHz Processor            2
Dimensity 920 5G, Octa Core, 2.5 GHz Processor          2
Snapdragon 712, Octa Core, 2.3 GHz Processor            2
Snapdragon 778G+, Octa Core Processor                   2
Dimensity  900, Octa Core, 2 GHz Processor              2
Exynos 9611, Octa Core, 2.3 GHz Processor               2
Helio P95, Octa Core, 2.2 GHz Processor                 2
Snapdragon  439 , Octa Core, 2 GHz Processor            2
Snapdragon  888, Octa Core, 2.84 GHz Processor          2
Snapdragon  750G , Octa Core, 2.2 GHz Processor         2
Dimensity  900 5G, Octa Core, 2.4 GHz Processor         2
Exynos 9825, Octa Core, 2.73 GHz Processor              2
Snapdragon 7 Gen1, Octa Core, 2.36 GHz Processor        2
Helio G37, Octa Core, 1.8 GHz Processor                 2
Dimensity 8100, Octa Core, 2.85 GHz Processor           2
Tiger T616, Octa Core, 2 GHz Processor                  2
Unisoc  T610, Octa Core, 1.8 GHz Processor              2
Dimensity 700, Octa Core, 2 GHz Processor               2
Snapdragon 690, Octa Core, 2 GHz Processor              2
Unisoc  SC9863a, Octa Core, 1.6 GHz Processor           2
Snapdragon  765G , Octa Core, 2.4 GHz Processor         2
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor         2
Unisoc T612, Octa Core, 1.8 GHz Processor               2
Helio P35 , Octa Core, 2.3 GHz Processor                2
Snapdragon 865 , Octa Core, 2.84 GHz Processor          2
Snapdragon  778G Plus, Octa Core, 2.5 GHz Processor     2
Snapdragon  720G, Octa Core, 2.3 GHz Processor          2
Snapdragon 678, Octa Core, 2.2 GHz Processor            2
Dimensity  9000, Octa Core, 3.05 GHz Processor          2
Helio G85 , Octa Core, 2 GHz Processor                  2
Snapdragon 855+, Octa Core, 2.96 GHz Processor          2
Bionic  A15, Hexa Core, 3.22 GHz Processor              2
Dimensity 700 , Octa Core, 2.2 GHz Processor            2
Tiger  T310, Quad Core, 2 GHz Processor                 2
Snapdragon 6 Gen 1, Octa Core, 2.2 GHz Processor        2
Snapdragon 778G+, Octa Core, 2.5 GHz Processor          2
Dimensity 800U , Octa Core, 2.4 GHz Processor           2
Snapdragon 662 , Octa Core, 2 GHz Processor             2
Unisoc  T606, Octa Core, 2 GHz Processor                2
Exynos 9820, Octa Core, 2.7 GHz Processor               2
Helio P60, Octa Core, 2 GHz Processor                   2
Snapdragon 439, Octa Core, 2 GHz Processor              2
Snapdragon 460, Octa Core, 1.8 GHz Processor            2
Snapdragon  675, Octa Core, 2 GHz Processor             2
Exynos 1200, Octa Core, 2.4 GHz Processor               1
 Snapdragon 695, Octa Core, 2.2 GHz Processor           1
Quad Core, 1.4 GHz Processor                            1
Snapdragon 460 , Octa Core, 1.8 GHz Processor           1
Bionic A16                                              1
Dimensity  900, Octa Core, 2.4 GHz Processor            1
Dimensity 900, Octa Core, 2.4 GHz Processor             1
Exynos  2300, Octa Core Processor                       1
Tiger T310, Quad Core, 2 GHz Processor                  1
Tiger T7150, Quad Core, 1.8 GHz Processor               1
Helio  P22 , Octa Core, 2 GHz Processor                 1
Exynos 1380, Octa Core Processor                        1
Google Tensor G2, Octa Core, 2.85 GHz Processor         1
Dimensity 930, Octa Core, 2.2 GHz Processor             1
Apple  A13                                              1
Dimensity  1200 Max, Octa Core, 3 GHz Processor         1
Bionic A16, Hexa Core Processor                         1
Snapdragon 870 , Octa Core, 3.2 GHz Processor           1
Helio P23, Octa Core, 2.5 GHz Processor                 1
Snapdragon MSM8939, Octa Core, 1.5 GHz Processor        1
Unisoc  A55, Octa Core, 1.6 GHz Processor               1
Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor         1
Octa Core, 1.8 GHz Processor                            1
Snapdragon 450, Octa Core, 1.8 GHz Processor            1
Snapdragon 710, Octa Core, 2.2 GHz Processor            1
Exynos 7885, Octa Core, 2.2 GHz Processor               1
Google  Tensor G2, Octa Core, 2.85 GHz Processor        1
Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Processor      1
Helio P70, Octa Core, 2.1 GHz Processor                 1
Helio  G90T, Octa Core, 2.05 GHz Processor              1
Helio P35, Octa Core, 1.8 GHz Processor                 1
Snapdragon  855, Octa Core, 2.8 GHz Processor           1
Tiger T700, Octa Core, 1.8 GHz Processor                1
Google Tensor, Octa Core, 2.8 GHz Processor             1
Unisoc  SC9836A, Quad Core, 1.6 GHz Processor           1
Helio  G37, Octa Core, 2.3 GHz Processor                1
Snapdragon 615, Octa Core, 1.5 GHz Processor            1
Helio MT6580, Quad Core, 1.3 GHz Processor              1
Helio  G95, Octa Core, 2.05 GHz Processor               1
Tiger T610, Octa Core, 1.82 GHz Processor               1
Snapdragon 8+ Gen 2, Octa Core Processor                1
Snapdragon 835, Octa Core, 2.35 GHz Processor           1
Unisoc  SC9832E, Quad Core, 1.4 GHz Processor           1
Sanpdragon 680, Octa Core, 2.4 GHz Processor            1
Snapdragon  720G , Octa Core, 2.3 GHz Processor         1
Snapdragon 888+ , Octa Core, 2.9 GHz Processor          1
Snapdragon  680 , Octa Core, 2.4 GHz Processor          1
Tiger T606, Octa Core, 2 GHz Processor                  1
Unisoc T606, Octa Core, 1.6 GHz Processor               1
Helio  P35, Octa Core, 2.3 GHz Processor                1
Snapdragon 801, Octa Core, 1.5 GHz Processor            1
Snapdragon 860, Octa Core, 2.96 GHz Processor           1
Snapdragon 775                                          1
Unisoc, Octa Core Processor                             1
Snapdragon 855, Octa Core, 2.8 GHz Processor            1
Snapdragon 730, Octa Core, 2.2 GHz Processor            1
Snapdragon  810, Octa Core, 2.4 GHz Processor           1
Bionic  A17, Octa Core Processor                        1
Exynos 1280, Octa Core Processor                        1
Spreadtrum  SC7731E, Quad Core, 1.3 GHz Processor       1
Tiger  T610, Octa Core, 1.8 GHz Processor               1
Snapdragon  6 Gen 1, Octa Core, 2.2 GHz Processor       1
Tiger T610, Quad Core, 1.8 GHz Processor                1
Dimensity  9200, Octa Core Processor                    1
Kirin  9000, Octa Core, 3.13 GHz Processor              1
Unisoc T610, Octa Core, 1.8 GHz Processor               1
Unisoc T117                                             1
Snapdragon 732G, Octa Core, 2.3 GHz Processor           1
Snapdragon 720G , Octa Core, 2.3 GHz Processor          1
Snapdragon 425, Quad Core, 1.4 GHz Processor            1
Fusion APL1024, Quad Core, 2.37 GHz Processor           1
Snapdragon  210, Quad Core, 1.1 GHz Processor           1
Snapdragon  765G, Octa Core, 2.4 GHz Processor          1
Exynos 9825, Octa Core, 2.7 GHz Processor               1
Exynos 7904, Octa Core, 1.8 GHz Processor               1
Snapdragon  865, Octa Core, 2.84 GHz Processor          1
Exynos  9611 , Octa Core, 2.3 GHz Processor             1
Helio P60, Octa Core, 1.99 GHz Processor                1
Snapdragon  782G, Octa Core, 2.7 GHz Processor          1
Dimensity 8100 Ultra, Octa Core, 2.85 GHz Processor     1
Spreadtrum  SC7731, Quad Core, 1.3 GHz Processor        1
Snapdragon 662, Octa Core, 2 GHz Processor              1
Kirin 9000E, Octa Core, 3.13 GHz Processor              1
Helio A25, Octa Core, 1.8 GHz Processor                 1
Snapdragon  712 , Octa Core, 2.3 GHz Processor          1
Unisoc SC7731E, Quad Core, 1.3 GHz Processor            1
Helio  P22, Octa Core, 2 GHz Processor                  1
Snapdragon  730G, Octa Core, 2.2 GHz Processor          1
Dimensity 9200, Octa Core Processor                     1
Snapdragon 730G, Octa Core, 2.2 GHz Processor           1
Exynos 9810, Octa Core, 2.7 GHz Processor               1
Dimensity 1100 5G, Octa Core, 2.6 GHz Processor         1
Octa Core, 2.2 GHz Processor                            1
Google Tensor 3, Octa Core Processor                    1
Snapdragon 8 Gen1 , Octa Core, 3 GHz Processor          1
Tiger T610, Octa Core, 1.8 GHz Processor                1
Kirin 990, Octa Core, 2.86 GHz Processor                1
Exynos 2100, Octa Core, 2.9 GHz Processor               1
Snapdragon 675, Octa Core, 2 GHz Processor              1
Snapdragon  662 , Octa Core, 2 GHz Processor            1
Exynos 9810, Octa Core, 2.8 GHz Processor               1
Exynos 1330, Octa Core Processor                        1
Snapdragon  778G+, Octa Core Processor                  1
Snapdragon 680 , Octa Core, 2.4 GHz Processor           1
Helio   G90T , Octa Core, 2.05 GHz Processor            1
(28 nm), Quad Core, 1.5 GHz Processor                   1
Kirin  810, Octa Core, 2.2 GHz Processor                1
Snapdragon 439, Octa Core, 1.95 GHz Processor           1
Helio  P65 , Octa Core, 2 GHz Processor                 1
Helio P70, Octa Core, 2 GHz Processor                   1
Samsung Exynos 7885, Octa Core, 2.2 GHz Processor       1
Qualcomm Snapdragon 670, Octa Core, 2 GHz Processor     1
Qualcomm Snapdragon 625, Octa Core, 2 GHz Processor     1
Snapdragon  7 Gen2, Octa Core Processor                 1
Snapdragon  7 Gen1, Octa Core, 2.4 GHz Processor        1
Kirin 659, Octa Core, 2.36 GHz Processor                1
Helio  G88, Octa Core, 2 GHz Processor                  1
Snapdragon  690 , Octa Core, 2 GHz Processor            1
Dimensity 1000+, Octa Core, 2.6 GHz Processor           1
Spreadtrum  SC9832E , Quad Core, 1.4 GHz Processor      1
Snapdragon 665, Octa Core, 2 GHz Processor              1
Snapdragon 425, Quad Core, 1.2 GHz Processor            1
Spreadtrum  SC9832E, Quad Core, 1.4 GHz Processor       1
Google  Tensor 3, Octa Core Processor                   1
Name: count, dtype: int64

In [78]:
df1['ram'].value_counts()

ram
8 GB RAM, 128 GB inbuilt     267
6 GB RAM, 128 GB inbuilt     190
4 GB RAM, 64 GB inbuilt      143
12 GB RAM, 256 GB inbuilt     70
8 GB RAM, 256 GB inbuilt      70
4 GB RAM, 128 GB inbuilt      62
3 GB RAM, 32 GB inbuilt       37
6 GB RAM, 64 GB inbuilt       29
2 GB RAM, 32 GB inbuilt       24
3 GB RAM, 64 GB inbuilt       15
12 GB RAM, 512 GB inbuilt     10
6 GB RAM, 256 GB inbuilt       7
16 GB RAM, 256 GB inbuilt      6
1 GB RAM, 16 GB inbuilt        6
4 GB RAM, 32 GB inbuilt        6
12 GB RAM, 128 GB inbuilt      4
2 GB RAM, 64 GB inbuilt        4
2 GB RAM, 16 GB inbuilt        4
6 GB RAM, 512 GB inbuilt       4
6 GB RAM, 1 TB inbuilt         4
16 GB RAM, 512 GB inbuilt      3
4 GB RAM, 256 GB inbuilt       3
3 GB RAM, 16 GB inbuilt        2
64 GB inbuilt                  2
8 GB RAM, 512 GB inbuilt       2
18 GB RAM, 512 GB inbuilt      1
512 MB RAM, 4 GB inbuilt       1
18 GB RAM, 256 GB inbuilt      1
512 GB inbuilt                 1
64 MB RAM, 128 MB inbuilt      1
4 GB RAM, 512 GB inbuilt       1
1 GB RAM, 8 GB inbuilt         1
12 GB RAM, 1 TB inbuilt        1
Name: count, dtype: int64

In [79]:
df1['display'].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          54
6.5 inches, 720 x 1600 px Display with Water Drop Notch              36
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           25
6.52 inches, 720 x 1600 px Display with Water Drop Notch             23
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            22
6.51 inches, 720 x 1600 px Display with Water Drop Notch             21
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole           19
6.43 inches, 1080 x 2400 px Display with Punch Hole                  16
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          15
6.53 inches, 720 x 1600 px Display with Water Drop Notch             14
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            14
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          11
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole           10
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.5 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       10
6.58 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch    10
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.6 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            10
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           9
6.6 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch       9
6.55 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            9
6.67 inches, 1080 x 2400 px Display with Punch Hole                   9
6.6 inches, 1080 x 2408 px Display with Water Drop Notch              9
6.7 inches, 1080 x 2400 px Display with Punch Hole                    8
6.58 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      8
6.6 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch      7
6.5 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              7
6.6 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole            7
6.58 inches, 1080 x 2408 px Display with Water Drop Notch             7
6.53 inches, 1080 x 2340 px Display with Water Drop Notch             7
6.58 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      7
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           7
6.59 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           7
6.1 inches, 1170 x 2532 px Display with Small Notch                   6
6.4 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       6
6.73 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           6
6.44 inches, 1080 x 2400 px Display with Water Drop Notch             6
6.67 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           5
6.56 inches, 720 x 1612 px Display with Water Drop Notch              5
6.1 inches, 1170 x 2532 px Display with Large Notch                   5
6.8 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            5
6.6 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            5
6.5 inches, 720 x 1560 px Display with Water Drop Notch               5
6.4 inches, 1080 x 2400 px Display with Punch Hole                    5
6.44 inches, 1080 x 2404 px, 90 Hz Display with Water Drop Notch      5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              5
6.67 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           5
6.35 inches, 720 x 1544 px Display with Water Drop Notch              4
6.6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            4
6.7 inches, 1290 x 2796 px, 120 Hz Display                            4
6.78 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           4
6.7 inches, 720 x 1600 px Display with Water Drop Notch               4
6.56 inches, 720 x 1600 px Display with Water Drop Notch              4
6.67 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           4
6.5 inches, 1600 x 720 px Display with Water Drop Notch               4
6.7 inches, 1080 x 2400 px Display with Water Drop Notch              4
6.56 inches, 1080 x 2376 px, 120 Hz Display with Punch Hole           4
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        4
6.78 inches, 1080 x 2448 px, 165 Hz Display                           4
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      3
6.2 inches, 720 x 1520 px Display with Water Drop Notch               3
6.47 inches, 1080 x 2400 px Display with Punch Hole                   3
6.1 inches, 1179 x 2556 px, 120 Hz Display                            3
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2408 px Display with Water Drop Notch             3
6.7 inches, 2400 x 1080 px Display with Punch Hole                    3
6.8 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            3
6.6 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        3
6.43 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           3
6.73 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           3
6.4 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           3
6.7 inches, 1284 x 2778 px, 120 Hz Display with Small Notch           3
6.44 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      3
6.51 inches, 1600 x 720 px Display with Punch Hole                    3
6.6 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole             3
6.7 inches, 1284 x 2778 px Display with Small Notch                   3
6.1 inches, 1170 x 2532 px, 120 Hz Display with Large Notch           3
8.03 inches, 1916 x 2160 px, 120 Hz Display                           3
7.1 inches, 1792 x 1920 px, 120 Hz Display with Punch Hole            3
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.6 inches, 2460 x 1080 px, 90 Hz Display with Punch Hole             3
5.4 inches, 1080 x 2340 px Display                                    3
6.59 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            3
6.6 inches, 720 x 1600 px Display with Water Drop Notch               3
6.44 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     3
6.8 inches, 1080 x 2460 px Display with Punch Hole                    3
4.7 inches, 750 x 1334 px Display                                     3
6.8 inches, 1116 x 2480 px, 120 Hz Display                            3
6.6 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole             3
6.78 inches, 1440 x 3200 px, 144 Hz Display with Punch Hole           3
5 inches, 854 x 480 px Display                                        3
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      2
6 inches, 1080 x 2160 px Display                                      2
6.4 inches, 1080 x 2340 px Display with Punch Hole                    2
6.22 inches, 720 x 1520 px Display with Water Drop Notch              2
6.22 inches, 1520 x 720 px Display with Water Drop Notch              2
6.5 inches, 1080 x 2400 px Display with Punch Hole                    2
6.1 inches, 828 x 1792 px Display with Large Notch                    2
6.6 inches, 1612 x 720 px Display with Water Drop Notch               2
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           2
6.8 inches, 1440 x 3040 px Display with Punch Hole                    2
6.6 inches, 2408 x 1080 px Display with Water Drop Notch              2
6.73 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.28 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Small Notch           2
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.73 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole             2
6.57 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           2
6 inches, 720 x 1440 px Display                                       2
6.3 inches, 1080 x 2340 px Display with Water Drop Notch              2
6.58 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole            2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole       2
6.49 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             2
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.71 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           2
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.56 inches, 1080 x 2376 px, 90 Hz Display with Small Notch           2
6.5 inches, 720 x 1600 px Display with Punch Hole                     2
5.5 inches, 1080 x 1920 px Display                                    2
6.18 inches, 1080 x 2246 px Display with Large Notch                  2
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           2
6.4 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        2
6.82 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.1 inches, 1080 x 2520 px, 120 Hz Display                            2
6.51 inches, 720 x 1600 px Display with Punch Hole                    2
6.8 inches, 1080 x 2460 px Display                                    2
6.71 inches, 720 x 1650 px Display with Water Drop Notch              2
5.45 inches, 720 x 1440 px Display                                    2
6.6 inches, 1080 x 2412 px, 144 Hz Display with Punch Hole            2
6.8 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            2
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1644 x 3840 px, 120 Hz Display                            2
6.44 inches, 1080 x 2400 px Display with Small Notch                  2
6.5 inches, 720 x 1560 px Display with Small Notch                    2
7.6 inches, 1812 x 2176 px, 120 Hz Display with Punch Hole            2
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.55 inches, 720 x 1612 px Display with Water Drop Notch              2
6.8 inches, 1440 x 3088 px, 120 Hz Display with Punch Hole            1
6.67 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
6.8 inches, 1080 x 2400 px, 165 Hz Display                            1
6.51 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.4 inches, 720 x 1600 px Display with Water Drop Notch               1
6.34 inches, 1080 x 2400 px Display with Punch Hole                   1
6.5 inches, 1600 x 720 px, 90 Hz Display with Punch Hole              1
6.09 inches, 1520 x 720 px Display with Water Drop Notch              1
6.67 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
6.5 inches, 720 x 1544 px Display with Water Drop Notch               1
6.5 inches, 1440 x 3168 px Display with Water Drop Notch              1
6.53 inches, 1176 x 2400 px Display with Large Notch                  1
6.4 inches, 720 x 1560 px Display with Punch Hole                     1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
6.55 inches, 1612 x 720 px, 90 Hz Display with Water Drop Notch       1
6.83 inches, 1200 x 2860 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1200 x 2400 px, 120 Hz Display with Punch Hole            1
5.7 inches, 1080 x 2280 px Display                                    1
6.4 inches, 1440 x 3040 px Display with Punch Hole                    1
6.2 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.8 inches, 1080 x 2520 px, 120 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2400 px Display with Punch Hole                   1
6.73 inches, 1290 x 2796 px, 120 Hz Display                           1
6.71 inches, 1440 x 3214 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1600 x 720 px Display with Punch Hole                     1
6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole              1
6.81 inches, 1080 x 2388 px Display                                   1
7.8 inches, 1440 x 1920 px Display                                    1
6.82 inches, 720 x 1640 px, 90 Hz Display with Punch Hole             1
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             1
6.53 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
6.2 inches, 1520 x 720 px Display with Water Drop Notch               1
6.8 inches, 1080 x 2448 px, 165 Hz Display                            1
6.81 inches, 1080 x 2400 px Display with Punch Hole                   1
4.7 inches, 1080 x 1920 px Display                                    1
6.06 inches, 1170 x 2532 px, 120 Hz Display with Punch Hole           1
6.82 inches, 720 x 1640 px, 90 Hz Display with Water Drop Notch       1
5.9 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       1
6.9 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            1
6.1 inches, 828 x 1792 px Display                                     1
5.4 inches, 1080 x 2340 px Display with Large Notch                   1
6.9 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole             1
5.42 inches, 1080 x 2340 px Display with Punch Hole                   1
6.36 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.2 inches, 720 x 1680 px Display                                     1
7.92 inches, 2088 x 2250 px Display                                   1
6.52 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.82 inches, 1640 x 720 px, 90 Hz Display with Punch Hole             1
4.5 inches, 480 x 854 px Display                                      1
8.03 inches, 1916 x 2160 px, 120 Hz Display with Punch Hole           1
6.74 inches, 1212 x 2616 px, 120 Hz Display                           1
2.8 inches, 240 x 320 px Display                                      1
6.66 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.67 inches, 1080 x 2160 px, 90 Hz Display with Punch Hole            1
6.8 inches, 1080 x 2400 px, 120 Hz Display                            1
6.64 inches, 1080 x 2388 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.28 inches, 1080 x 2280 px Display                                   1
6 inches, 1440 x 2880 px Display                                      1
6 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole               1
6.73 inches, 1440 x 3412 px, 144 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             1
6.8 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
6.62 inches, 2408 x 1080 px Display with Punch Hole                   1
6.74 inches, 720 x 1600 px Display with Water Drop Notch              1
3.54 inches, 640 x 960 px Display                                     1
6.67 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            1
6.9 inches, 1400 x 3200 px, 120 Hz Display with Punch Hole            1
6.55 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.6 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.5 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch        1
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            1
6.95 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.7 inches, 720 x 1650 px Display with Punch Hole                     1
8.02 inches, 1914 x 2160 px, 120 Hz Display with Punch Hole           1
6.78 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole            1
6.92 inches, 1080 x 2460 px, 144 Hz Display                           1
6.51 inches, 1080 x 2408 px, 144 Hz Display with Punch Hole           1
6.2 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.43 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2448 px, 144 Hz Display                           1
7.6 inches, 1768 x 2208 px, 120 Hz Display with Punch Hole            1
6.58 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
6.7 inches, 1080 x 2460 px, 165 Hz Display with Punch Hole            1
6.6 inches, 1080 x 2460 px, 90 Hz Display with Water Drop Notch       1
5.5 inches, 720 x 1440 px Display                                     1
6.9 inches, 1440 x 3200 px Display with Punch Hole                    1
6.5 inches, 1242 x 2688 px Display with Large Notch                   1
6.5 inches, 1080 x 2400 px, 120 Hz Display                            1
6.78 inches, 1080 x 2400 px, 120 Hz Display                           1
6.7 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      1
6.78 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
2.4 inches, 240 x 320 px Display                                      1
6.5 inches, 1644 x 3840 px Display                                    1
6.76 inches, 1344 x 2772 px, 90 Hz Display with Punch Hole            1
6.57 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.44 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.76 inches, 1344 x 2772 px, 120 Hz Display with Punch Hole           1
6.67 inches, 2400 x 1080 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2460 px Display with Water Drop Notch              1
6.5 inches, 1080 x 2340 px Display                                    1
6.68 inches, 1284 x 2778 px, 120 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch      1
6.54 inches, 720 x 1560 px Display with Small Notch                   1
4.7 inches, 750 x 1334 px Display with Large Notch                    1
6.7 inches, 1080 x 2400 px, 165 Hz Display                            1
6.5 inches, 720 x 1600 px Display with Small Notch                    1
6.1 inches, 720 x 1560 px Display with Water Drop Notch               1
6.56 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.4 inches, 1080 x 2408 px Display with Water Drop Notch              1
6.91 inches, 1080 x 2460 px Display with Punch Hole                   1
6.82 inches, 720 x 1600 px Display with Water Drop Notch              1
7.4 inches, 1440 x 3200 px Display                                    1
6.43 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.38 inches, 1080 x 2340 px Display with Water Drop Notch             1
6.67 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.76 inches, 1440 x 3200 px, 120 Hz Display with Small Notch          1
7.8 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole            1
6.73 inches, 1080 x 2448 px, 165 Hz Display                           1
6.14 inches, 1080 x 2400 px Display with Punch Hole                   1
6.1 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
5 inches, 720 x 1280 px Display                                       1
6.52 inches, 720 x 1560 px Display with Punch Hole                    1
6.62 inches, 1080 x 2412 px, 144 Hz Display with Water Drop Notch     1
6.06 inches, 1170 x 2532 px Display with Punch Hole                   1

In [82]:
df1['battery'].value_counts()

battery
5000 mAh Battery with 33W Fast Charging      103
5000 mAh Battery with 18W Fast Charging       89
5000 mAh Battery                              74
5000 mAh Battery with 67W Fast Charging       30
5000 mAh Battery with 10W Fast Charging       28
5000 mAh Battery with 15W Fast Charging       24
5000 mAh Battery with 25W Fast Charging       23
5000 mAh Battery with 120W Fast Charging      21
5000 mAh Battery with 80W Fast Charging       19
6000 mAh Battery with 18W Fast Charging       19
5000 mAh Battery with Fast Charging           18
5000 mAh Battery with 30W Fast Charging       15
4500 mAh Battery with 33W Fast Charging       14
6000 mAh Battery with 15W Fast Charging       13
4500 mAh Battery with 65W Fast Charging       12
4000 mAh Battery                              12
4500 mAh Battery with 25W Fast Charging       12
4500 mAh Battery with 80W Fast Charging       12
4500 mAh Battery with 67W Fast Charging       11
4700 mAh Battery with 80W Fast Charging        9
5000 mAh Battery with 44W Fast Charging        8
4700 mAh Battery with 66W Fast Charging        7
4230 mAh Battery                               7
5000 mAh Battery with 65W Fast Charging        6
5000 mAh Battery with 20W Fast Charging        6
6000 mAh Battery with 65W Fast Charging        6
4300 mAh Battery with 30W Fast Charging        6
4000 mAh Battery with 33W Fast Charging        6
5000 mAh Battery with 45W Fast Charging        6
4800 mAh Battery with 150W Fast Charging       5
4500 mAh Battery with Fast Charging            5
4600 mAh Battery with 66W Fast Charging        5
4700 mAh Battery with 120W Fast Charging       5
5020 mAh Battery with 18W Fast Charging        5
5080 mAh Battery with 67W Fast Charging        5
4500 mAh Battery with 66W Fast Charging        4
6000 mAh Battery with 25W Fast Charging        4
4300 mAh Battery with 44W Fast Charging        4
5500 mAh Battery with 67W Fast Charging        4
5020 mAh Battery with 33W Fast Charging        4
4800 mAh Battery with 66W Fast Charging        4
6000 mAh Battery                               4
6000 mAh Battery with 33W Fast Charging        4
4323 mAh Battery with Fast Charging            4
4500 mAh Battery with 45W Fast Charging        4
5000 mAh Battery with 100W Fast Charging       4
4000 mAh Battery with Fast Charging            4
4500 mAh Battery with 120W Fast Charging       4
3000 mAh Battery                               4
4400 mAh Battery with 66W Fast Charging        3
4400 mAh Battery with 25W Fast Charging        3
4600 mAh Battery with 120W Fast Charging       3
4050 mAh Battery with 44W Fast Charging        3
7000 mAh Battery with 33W Fast Charging        3
4800 mAh Battery with 67W Fast Charging        3
3700 mAh Battery with 25W Fast Charging        3
3500 mAh Battery                               3
3095 mAh Battery with Fast Charging            3
3200 mAh Battery with Fast Charging            3
4352 mAh Battery with Fast Charging            3
4030 mAh Battery                               3
4520 mAh Battery with 33W Fast Charging        3
4500 mAh Battery with 44W Fast Charging        3
3240 mAh Battery with Fast Charging            3
4980 mAh Battery with 120W Fast Charging       3
3279 mAh Battery with Fast Charging            3
4325 mAh Battery with Fast Charging            3
5000 mAh Battery with 66W Fast Charging        3
4250 mAh Battery with 33W Fast Charging        3
4500 mAh Battery with 60W Fast Charging        3
4000 mAh Battery with 15W Fast Charging        3
4000 mAh Battery with 25W Fast Charging        3
4300 mAh Battery with 65W Fast Charging        3
4300 mAh Battery with 66W Fast Charging        3
4000 mAh Battery with 66W Fast Charging        3
6000 mAh Battery with 44W Fast Charging        3
5000 mAh Battery with 22.5W Fast Charging      3
4350 mAh Battery with 120W Fast Charging       2
3360 mAh Battery                               2
4200 mAh Battery with 65W Fast Charging        2
4000 mAh Battery with 18W Fast Charging        2
5050 mAh Battery with 18W Fast Charging        2
4500 mAh Battery with 30W Fast Charging        2
4000 mAh Battery with 21W Fast Charging        2
3300 mAh Battery                               2
5160 mAh Battery with 67W Fast Charging        2
4410 mAh Battery with Fast Charging            2
5160 mAh Battery with 45W Fast Charging        2
4200 mAh Battery with 33W Fast Charging        2
4610 mAh Battery with 125W Fast Charging       2
6000 mAh Battery with Fast Charging            2
3020 mAh Battery                               2
4500 mAh Battery with 100W Fast Charging       2
4200 mAh Battery with 44W Fast Charging        2
6000 mAh Battery with 20W Fast Charging        2
3500 mAh Battery with Fast Charging            2
5003 mAh Battery with 30W Fast Charging        2
4700 mAh Battery with 67W Fast Charging        2
3110 mAh Battery                               2
4830 mAh Battery with 66W Fast Charging        2
4020 mAh Battery with 33W Fast Charging        2
4400 mAh Battery with 68W Fast Charging        2
4200 mAh Battery with 40W Fast Charging        2
4500 mAh Battery with 150W Fast Charging       2
4200 mAh Battery with 55W Fast Charging        2
4450 mAh Battery with 125W Fast Charging       2
4000 mAh Battery with 10W Fast Charging        2
4500 mAh Battery with 18W Fast Charging        2
4300 mAh Battery with 25W Fast Charging        2
2438 mAh Battery with Fast Charging            1
5100 mAh Battery with 40W Fast Charging        1
4600 mAh Battery with 125W Fast Charging       1
4200 mAh Battery with 120W Fast Charging       1
2150 mAh Battery                               1
3060 mAh Battery with Fast Charging            1
4300 mAh Battery with 120W Fast Charging       1
4355 mAh Battery with 30W Fast Charging        1
6000 mAh Battery with 80W Fast Charging        1
4800 mAh Battery with 68W Fast Charging        1
4520 mAh Battery with 67W Fast Charging        1
2800 mAh Battery                               1
4352 mAh Battery with 25W Fast Charging        1
5200 mAh Battery with 33W Fast Charging        1
3900 mAh Battery with 25W Fast Charging        1
4820 mAh Battery with 120W Fast Charging       1
4310 mAh Battery with 50W Fast Charging        1
4810 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 100W Fast Charging       1
5200 mAh Battery with 210W Fast Charging       1
4700 mAh Battery with 45W Fast Charging        1
4700 mAh Battery with 200W Fast Charging       1
5200 mAh Battery with 67W Fast Charging        1
2050 mAh Battery with Fast Charging            1
4500 mAh Battery with 180W Fast Charging       1
4614 mAh Battery with 30W Fast Charging        1
4450 mAh Battery                               1
3300 mAh Battery with 15W Fast Charging        1
5000 mAh Battery with 19W Fast Charging        1
2275 mAh Battery                               1
4860 mAh Battery with 67W Fast Charging        1
5160 mAh Battery with 33W Fast Charging        1
4870 mAh Battery with 120W Fast Charging       1
1900 mAh Battery                               1
4050 mAh Battery with 40W Fast Charging        1
4700 mAh Battery with 33W Fast Charging        1
4100 mAh Battery with 15W Fast Charging        1
3520 mAh Battery with Fast Charging            1
1500 mAh Battery                               1
6000 mAh Battery with 45W Fast Charging        1
4730 mAh Battery with 80W Fast Charging        1
4470 mAh Battery with 18W Fast Charging        1
5600 mAh Battery with 68W Fast Charging        1
5050 mAh Battery with 10W Fast Charging        1
4300 mAh Battery with 210W Fast Charging       1
5000 mAh Battery with 60W Fast Charging        1
4080 mAh Battery with 18W Fast Charging        1
5000 mAh Battery with 135W Fast Charging       1
5000 mAh Battery with 165W Fast Charging       1
2800 mAh Battery with Fast Charging            1
4300 mAh Battery with 33W Fast Charging        1
4200 mAh Battery with 66W Fast Charging        1
21000 mAh Battery with 33W Fast Charging       1
6000 mAh Battery with 120W Fast Charging       1
4700 mAh Battery with Fast Charging            1
4600 mAh Battery with 240W Fast Charging       1
5100 mAh Battery with 45W Fast Charging        1
1821 mAh Battery with 18W Fast Charging        1
4500 mAh Battery with 50W Fast Charging        1
1150 mAh Battery                               1
9800 mAh Battery with 66W Fast Charging        1
3500 mAh Battery with 18W Fast Charging        1
2230 mAh Battery                               1
4500 mAh Battery with 20W Fast Charging        1
4800 mAh Battery with 125W Fast Charging       1
4000 mAh Battery with 45W Fast Charging        1
4015 mAh Battery with 30W Fast Charging        1
4300 mAh Battery with 45W Fast Charging        1
4020 mAh Battery with 68W Fast Charging        1
3285 mAh Battery with Fast Charging            1
4300 mAh Battery with 67W Fast Charging        1
5100 mAh Battery with 120W Fast Charging       1
4300 mAh Battery with Fast Charging            1
4000 mAh Battery with 20W Fast Charging        1
4000 mAh Battery with 30W Fast Charging        1
4000 mAh Battery with 22.5W Fast Charging      1
4830 mAh Battery with 67W Fast Charging        1
5020 mAh Battery with 67W Fast Charging        1
4800 mAh Battery with 25W Fast Charging        1
3700 mAh Battery with Fast Charging            1
4200 mAh Battery with 67W Fast Charging        1
3315 mAh Battery                               1
5080 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 18W Fast Charging        1
5050 mAh Battery                               1
4800 mAh Battery                               1
4360 mAh Battery with 66W Fast Charging        1
4310 mAh Battery with 30W Fast Charging        1
4800 mAh Battery with 33W Fast Charging        1
3600 mAh Battery with 18W Fast Charging        1
7000 mAh Battery with Fast Charging            1
2000 mAh Battery                               1
3100 mAh Battery with 15W Fast Charging        1
4100 mAh Battery                               1
22000 mAh Battery with 33W Fast Charging       1
7000 mAh Battery                               1
5020 mAh Battery with 22.5W Fast Charging      1
5000 mAh Battery with 40W Fast Charging        1
7000 mAh Battery with 18W Fast Charging        1
2400 mAh Battery                               1
4350 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 27W Fast Charging        1
3200 mAh Battery                               1
2500 mAh Battery                               1
3700 mAh Battery with 18W Fast Charging        1
4532 mAh Battery with Fast Charging            1
3000 mAh Battery with 10W Fast Charging        1
5050 mAh Battery with 30W Fast Charging        1
5065 mAh Battery with 67W Fast Charging        1
4620 mAh Battery with 18W Fast Charging        1
4100 mAh Battery with 33W Fast Charging        1
4780 mAh Battery with 30W Fast Charging        1
3730 mAh Battery with Fast Charging            1
4500 mAh Battery with 55W Fast Charging        1
3400 mAh Battery with Fast Charging            1
2730 mAh Battery                               1
5180 mAh Battery with 10W Fast Charging        1
4500 mAh Battery with 68W Fast Charging        1
8000 mAh Battery                               1
5000 mAh Battery with 68W Fast Charging        1
5000 mAh Battery with 68.2W Fast Charging      1
Name: count, dtype: int64

In [87]:
df1['model'].str.split(' ').str.get(0)

0         OnePlus
1         OnePlus
2         Samsung
3        Motorola
4          Realme
5         Samsung
6           Apple
7          Xiaomi
8         Nothing
9         OnePlus
10         Realme
11           Oppo
12         Xiaomi
13           Vivo
14        Samsung
15          Apple
16           Vivo
17           OPPO
18        OnePlus
19           Vivo
20        OnePlus
21           Vivo
22           Poco
23         Xiaomi
24           Vivo
25        Samsung
26        OnePlus
27          Apple
28           Vivo
29        OnePlus
30         Realme
31           Poco
32           Vivo
33          Apple
34        Samsung
35        Samsung
36           Oppo
37        Samsung
38         Xiaomi
39           OPPO
40        OnePlus
41         Xiaomi
42       Motorola
43         Realme
44           Vivo
45        Samsung
46         Xiaomi
47         Realme
48           Vivo
49        Samsung
50        Samsung
51           iQOO
52            Jio
53       Motorola
54         Realme
55         Realme
56          Apple
57         Xiaomi
58        Samsung
59       Motorola
60         Xiaomi
61           Vivo
62        Samsung
63           Vivo
64           Poco
65           Vivo
66        OnePlus
67         Xiaomi
68        Samsung
69           Oppo
70           OPPO
71           Vivo
72           iQOO
73        OnePlus
74         Xiaomi
75         Gionee
76          Apple
77           OPPO
78        Samsung
79         Xiaomi
80       Motorola
81        Samsung
82         Realme
83           Vivo
84        Samsung
85       Motorola
86        Samsung
87           OPPO
88         Xiaomi
89        Samsung
90           Vivo
91        OnePlus
92       Motorola
93           Vivo
94         Realme
95         Realme
96           OPPO
97           iQOO
98           Vivo
99           Vivo
100         Apple
101        Xiaomi
102      Motorola
103        Realme
104          OPPO
105        Xiaomi
106          Vivo
107       Samsung
108          Vivo
109       OnePlus
110         Tecno
111         Apple
112        Xiaomi
113       Samsung
114        Xiaomi
115          OPPO
116       Samsung
117          iQOO
118         Tesla
119       Samsung
120      Motorola
121       OnePlus
122        Google
123       Infinix
124       Samsung
125          Vivo
126      Motorola
127       OnePlus
128       Samsung
129        Google
130        Xiaomi
131        Xiaomi
132      Motorola
133       Nothing
134          Poco
135        Xiaomi
136         Apple
137        Realme
138          OPPO
139          iQOO
140          iQOO
141          OPPO
142          Poco
143           Jio
144       OnePlus
145       Samsung
146          iQOO
147       Samsung
148        Xiaomi
149         Apple
150        Xiaomi
151      Motorola
152         Apple
153          Oppo
154       Infinix
156        Realme
157          OPPO
158        Realme
159          Oppo
160        Realme
161          Cola
162         Apple
163          Oppo
164          Vivo
165       Samsung
166        Xiaomi
167        Realme
168          iQOO
169       Infinix
170          Letv
171        Xiaomi
172        Realme
173          OPPO
174         Apple
175          iQOO
176        Xiaomi
177        Realme
178          Vivo
179          Vivo
180          POCO
181       Infinix
182         Tecno
183      Motorola
184       Samsung
185        Realme
186       OnePlus
187      Motorola
188         iKall
189         LeEco
190        Realme
191        Duoqin
192       Samsung
193         Nokia
194      Motorola
195        Realme
196          OPPO
197       OnePlus
198          Poco
199       Samsung
200          OPPO
201       Samsung
202      Motorola
203        Xiaomi
204      Motorola
205          Poco
206       Nothing
207       Samsung
208         Tecno
209        Xiaomi
210         Apple
211          Vivo
212        Realme
213        Realme
214          Lava
215         Honor
216        Google
217         Tecno
218          Vivo
219       Samsung
220        Xiaomi
221        Realme
222        Realme
223      Motorola
224        Xiaomi
225          Vivo
226          POCO
227        Realme
228        Realme
229          OPPO
230       OnePlus
231          iQOO
232          Vivo
233        Xiaomi
234          OPPO
235          Vivo
236        Xiaomi
237          Vivo
238          OPPO
239          Vivo
240        Xiaomi
241          OPPO
242       Samsung
243          Vivo
244        Google
245        Xiaomi
246          OPPO
247         Apple
248      Motorola
249         Nubia
250      Motorola
251         Tecno
252       Infinix
253          iQOO
254        Xiaomi
255          OPPO
256       Samsung
257       Samsung
258          Vivo
259      Motorola
260          Poco
261         Tecno
262          POCO
263         Apple
264       Samsung
265       Infinix
266          OPPO
267       OnePlus
268         Redmi
269       Nothing
270       Samsung
272        Google
273       Infinix
274        Xiaomi
275        Xiaomi
276        Xiaomi
277         Apple
278         Tecno
279        Realme
280          Asus
281          Vivo
282         Apple
283        Xiaomi
284          iQOO
285       Samsung
286        Xiaomi
287        Xiaomi
288       Infinix
289       Infinix
290         Apple
291       Samsung
292          Poco
293        Xiaomi
294        Realme
295       Samsung
296      Motorola
297          OPPO
298        Xiaomi
299        Xiaomi
300          Vivo
301        Xiaomi
302        Realme
303      Motorola
304        Xiaomi
305        Xiaomi
306       Samsung
307         Apple
308       OnePlus
309       Samsung
310          OPPO
311       OnePlus
312       Samsung
313       Samsung
314      Motorola
315          itel
316          Vivo
317       Samsung
318          POCO
319         Honor
320          iQOO
321       Samsung
322        Royole
323         Apple
324       Samsung
325         Tecno
326        Google
327        Xiaomi
328       Samsung
329       Infinix
330          Vivo
331          OPPO
332          iQOO
333       Samsung
334        Realme
335          Poco
336       Infinix
337       Samsung
338      Motorola
339       OnePlus
340        Xiaomi
341        Xiaomi
342         Tecno
343       Samsung
344          POCO
345       OnePlus
346         Apple
347          Oppo
348          Vivo
349      Motorola
350      Motorola
351        Xiaomi
352           Jio
353          Vivo
354        Xiaomi
355        Realme
356          Vivo
357          OPPO
358        Xiaomi
359          Poco
360        Realme
361        Xiaomi
362          iQOO
363         Apple
364       Samsung
365          OPPO
366       OnePlus
367         Tecno
368       Samsung
369        Xiaomi
370          Sony
371          Vivo
372          Poco
373       Samsung
374        Google
375       Samsung
377        Realme
378          OPPO
379        Realme
380       Samsung
381       Samsung
382          Vivo
383          Letv
384         Tecno
385          iQOO
386          Vivo
387        Realme
388       Samsung
389        Realme
390        Realme
391          OPPO
392          OPPO
393       Samsung
394       Oukitel
395        Realme
396        Xiaomi
397       Samsung
398        Xiaomi
399          itel
401        Realme
402         Apple
403          Poco
404       Samsung
405        Realme
406        Xiaomi
407          Vivo
408          OPPO
409        Xiaomi
410          Asus
411          Oppo
412        Realme
413       Samsung
414       OnePlus
415        Xiaomi
416          OPPO
417        Realme
418        Xiaomi
419         Redmi
420         Apple
421      Motorola
422      Motorola
423        Xiaomi
424         Honor
425       OnePlus
426          Vivo
427          OPPO
428        Xiaomi
429         Nokia
430        Xiaomi
431         Vertu
432       Samsung
433         Tecno
434          Poco
435           BLU
436          OPPO
437      Motorola
438        Xiaomi
439         Apple
440       Samsung
441          Poco
442        Xiaomi
443       Samsung
444      Motorola
445          Asus
446        Xiaomi
447       Infinix
448         Apple
449        Realme
450       Infinix
451          Vivo
452          Vivo
453         Tecno
454       Samsung
455         Redmi
456          Asus
457          Sony
458          iQOO
459         Tecno
460        Xiaomi
461       Samsung
462        Xiaomi
463          OPPO
464         Nubia
465       Samsung
466         Nokia
467       Infinix
468          Vivo
469          OPPO
470        Xiaomi
471        Realme
472       Infinix
474       Samsung
475       Samsung
476        Xiaomi
477          Vivo
478           Lyf
479      Motorola
480         Tecno
481          Itel
482          Vivo
483        Huawei
484       Samsung
485          iQOO
486         Nokia
487          Sony
488          Vivo
489          Sony
490         Tecno
491        Huawei
492          Vivo
493         Nubia
494      Motorola
495          iQOO
496       Samsung
497          POCO
498        Realme
499          Vivo
500         Honor
501        Xiaomi
502        Realme
503      Motorola
504       Samsung
505       OnePlus
506        Google
507        Xiaomi
508         Honor
509        Realme
510          Vivo
511       Samsung
512       Samsung
513        Realme
514          POCO
515        Google
516       OnePlus
517        Xiaomi
518       Samsung
519          Oppo
520          Vivo
521          iQOO
522          OPPO
523        Realme
524          Vivo
525      Motorola
526        Realme
527         Apple
528          Vivo
529       Samsung
530          Vivo
531        Xiaomi
534       OnePlus
535        Google
536         Nokia
537       Infinix
538          Poco
539        Xiaomi
540           ZTE
541        Xiaomi
542          OPPO
543        Huawei
544       Samsung
545        Lenovo
546          Vivo
547         Nokia
548        Realme
549        Realme
550         Nokia
552          Poco
553        Xiaomi
554          iQOO
555        Realme
556       Samsung
557        Xiaomi
558      Motorola
559       OnePlus
560          OPPO
561          Poco
562          OPPO
563          POCO
564        Realme
565          Asus
566        Realme
567       Samsung
568         Nubia
569       Samsung
570            LG
571        Xiaomi
572       Samsung
574          Vivo
576       Samsung
577          Oppo
578          Oppo
579          OPPO
580         Nokia
581          OPPO
583      Motorola
584          Oppo
585          iQOO
586         Nokia
587       Samsung
588          OPPO
589        Xiaomi
590         Tecno
591        Realme
592        Xiaomi
593          iQOO
594          iQOO
595        Realme
596        Xiaomi
597           Jio
598        Xiaomi
599        Xiaomi
600          Vivo
601       Samsung
602          Vivo
603        Realme
604       OnePlus
605       Samsung
606         Apple
607         Apple
609          Sony
610       Samsung
612        Xiaomi
613       Oukitel
614          Vivo
615          Poco
616        Xiaomi
617        Realme
618          Vivo
619        Xiaomi
620          Lava
621        Realme
622          OPPO
623          POCO
624        Realme
625          OPPO
626          Vivo
627         Nokia
628         Apple
629          Sony
630      Motorola
631       Samsung
632       Samsung
633        Xiaomi
634        Realme
635        Realme
636         Apple
637          iQOO
638         Tecno
639       OnePlus
641       Samsung
642          POCO
643        Xiaomi
644          Vivo
646       Samsung
648          Vivo
649        Huawei
650      Micromax
651          Asus
652        Realme
653        Realme
654          OPPO
655        Xiaomi
656         Apple
658          Letv
659       OnePlus
660          Vivo
661          OPPO
662          Vivo
663       Infinix
664        Realme
666          itel
667          OPPO
668        Xiaomi
669         Honor
670         Tecno
671       Infinix
672        Realme
673       Samsung
674         Tecno
675        Xiaomi
676        Xiaomi
677        Xiaomi
678        Xiaomi
679        Xiaomi
680            LG
681      Motorola
682            LG
683       Samsung
684       Samsung
686          iQOO
687       Samsung
688          Vivo
689          Vivo
690          itel
691        Xiaomi
692          Poco
693          OPPO
694       Samsung
695       Infinix
696         Honor
697       Infinix
698          Sony
700         Nubia
701         Nokia
702        Xiaomi
703          Oppo
704         Apple
705          Vivo
706          OPPO
707       Samsung
708          OPPO
709          OPPO
710       OnePlus
711        Gionee
712          Poco
713          OPPO
714      Motorola
715       Samsung
716       Samsung
717          Vivo
718          Vivo
719          Vivo
720          Vivo
721          Asus
722      Motorola
723        Xiaomi
724        Huawei
725        Realme
726        Huawei
727          iQOO
728         Apple
729       Infinix
730         Tecno
731          Oppo
732          Vivo
733        Xiaomi
734        Huawei
735         Tecno
736        Huawei
737        Xiaomi
738         Nokia
739        Realme
740          OPPO
741      Motorola
742          Oppo
743          Poco
744          itel
745          Vivo
746        Xiaomi
747          Vivo
749       Samsung
750          Vivo
751          Oppo
752        Realme
753          Vivo
755        Xiaomi
756          Poco
758         iKall
759        Xiaomi
760          Vivo
761         Honor
762         Apple
763         Tecno
764         Apple
765        Google
766          Vivo
767      Motorola
768      Motorola
769          Vivo
770        Realme
771          Vivo
772         Honor
773       Samsung
774       Samsung
775          Vivo
776        Xiaomi
777          Oppo
778         Tecno
779          Vivo
780        Xiaomi
781         Apple
782          Vivo
783          Vivo
784       Samsung
785        Xiaomi
786      Micromax
787       Samsung
788          OPPO
789        Xiaomi
790        Xiaomi
791        Realme
792          OPPO
793          Oppo
794          itel
795        Xiaomi
796       Samsung
797          POCO
798       Samsung
799        Realme
800        Huawei
801          Vivo
802          Vivo
803          Vivo
804          Vivo
805       Samsung
806        Realme
807          Vivo
808       Samsung
809         Leitz
810        Xiaomi
811       Infinix
812        Realme
813         Apple
814         Apple
815        Xiaomi
816        Xiaomi
818         Nokia
819       OnePlus
820         Tecno
821        Realme
822        Xiaomi
823          OPPO
824       Infinix
825       Samsung
826       Samsung
827          Vivo
828          Poco
829       Infinix
830       Samsung
831          Vivo
832        Xiaomi
833        Xiaomi
834        Realme
836          Vivo
837          Vivo
838        Gionee
839        Xiaomi
840         Apple
841       Infinix
842        Realme
843        Xiaomi
844           CAT
845        Xiaomi
847        Realme
848        Xiaomi
849        Lenovo
850       Samsung
851        Realme
853         Apple
854        Xiaomi
855        Realme
856       Samsung
858          Oppo
859          Oppo
860          Sony
861          Vivo
862        Huawei
863          Vivo
864          Vivo
865        Xiaomi
866        Xiaomi
867      Motorola
868        Google
869       Samsung
870       Samsung
871        Huawei
872        Xiaomi
874        Doogee
875        Huawei
876          iQOO
877          Vivo
878          Poco
879         Nokia
880         Tecno
883          Vivo
884        Huawei
885        Huawei
886       Samsung
887       Infinix
888       OnePlus
889        Realme
890       OnePlus
891          iQOO
892        Xiaomi
893          Oppo
894        Royole
895         Tecno
896         Tecno
897         Tecno
898        Realme
899          Sony
900        Realme
901         Tecno
902          Poco
903      Motorola
904       OnePlus
905        Realme
906        Realme
907          Itel
908       Samsung
909          Oppo
910       OnePlus
911       Samsung
912       OnePlus
913         Apple
914         Apple
915          OPPO
916        Xiaomi
918          Oppo
919        Realme
920       Samsung
921        Xiaomi
922        Xiaomi
923        Realme
924          OPPO
926           Lyf
928         Apple
929          Vivo
931          Lava
933         Tecno
934          OPPO
935      Motorola
936        Xiaomi
937       Infinix
938         Tecno
939           ZTE
940         Honor
941        Xiaomi
942           TCL
943       Samsung
944       Nothing
945      Motorola
946       OnePlus
947        Realme
948       Samsung
949       Samsung
950       Infinix
951          POCO
952          iQOO
953          Vivo
954          Vivo
955          Oppo
956         Tecno
957          iQOO
958       Infinix
959        Xiaomi
960       Samsung
961         Apple
962         Nubia
963      Micromax
964         Nokia
965          Vivo
966          Oppo
967          Poco
968         Honor
969          OPPO
970        Realme
971          iQOO
972        Realme
973       Samsung
974        Realme
975        Google
976       Samsung
977       Samsung
978       Samsung
979        Xiaomi
980          Vivo
981          OPPO
982        Realme
983          itel
984        Realme
985        Xiaomi
986          Vivo
987       OnePlus
989         Sharp
990        Huawei
991       Samsung
992        Realme
993        Huawei
994       Samsung
995       Samsung
996          Vivo
997          Poco
998     Blackview
999         Honor
1001         OPPO
1002       Doogee
1003         Lava
1004     Motorola
1005        iKall
1006      Oukitel
1007       Xiaomi
1008     Motorola
1009       Xiaomi
1010       Realme
1011         Oppo
1012         itel
1013       Google
1014         Vivo
1015     Motorola
1016        Honor
1017         POCO
1018     Motorola
1019      Samsung
Name: model, dtype: object

### Created a new columns name is Brand_name ###

In [88]:
brand_names=df1['model'].str.split(' ').str.get(0)

In [89]:
df1.insert(1,'brand_name',brand_names)

In [90]:
df1.head()

,index,brand_name,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [94]:
#Make all the brand name is small letter
df1['brand_names']=df1['brand_name'].str.lower()

C:\Users\tanma\AppData\Local\Temp\ipykernel_12408\1778839700.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['brand_names']=df1['brand_name'].str.lower()

In [95]:
df1.head()

,index,brand_name,model,price,rating,sim,processor,ram,battery,display,camera,card,os,brand_names
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,oneplus
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,oneplus
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13,samsung
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,motorola
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13,realme

### Brack the sim collumns and find 5G , NFC ,IR Blaster ###

In [96]:
has_5g=df1['sim'].str.contains("5G")
has_nfc=df1['sim'].str.contains('NFC')
has_ir_blaster=df1['sim'].str.contains('IR Blaster')

In [ ]:
#Insurt 6th columns has_5g
df1.insert(6,'has_5g',has_5g)
#Insurt 6th columns has_nfc
df1.insert(7,'has_nfc',has_nfc)
#Insurt 6th columns has_ir_blaster
df1.insert(6,'has_ir_blaster',has_ir_blaster)

In [120]:
df1.head()

,index,brand_name,model,price,rating,sim,has_ir_blaster,has_5g,has_nfc,processor,processor_name,processor_speed,num_cores,ram,battery,display,camera,card,os,brand_names
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",False,True,True,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,3.2 GHz Processor,Octa Core,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,oneplus
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,2.2 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,oneplus
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,2.4 GHz Processor,Octa Core,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13,samsung
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,2.2 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,motorola
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,2.6 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13,realme

### Brack the processor collumns and find processor_name , num_cores ,processor_name ###

In [121]:
processor_name=df1['processor'].str.split(',').str.get(0)
num_cores=df1['processor'].str.split(',').str.get(1)
processor_speed=df1['processor'].str.split(',').str.get(2)

In [123]:
##Insurt 10th columns processor_name
df1.insert(10,'processor_name',processor_name)
##Insurt 11th columns num_cores
df1.insert(11,'num_cores',num_cores)
##Insurt 10th columns processor_speed
df1.insert(12,'processor_speed',processor_speed)

ValueError: cannot insert processor_name, already exists

In [114]:
df1.head()

,index,brand_name,model,price,rating,sim,has_ir_blaster,has_5g,has_nfc,processor,processor_name,processor_speed,num_cores,ram,battery,display,camera,card,os,brand_names
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",False,True,True,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,3.2 GHz Processor,Octa Core,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,oneplus
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,2.2 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,oneplus
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,2.4 GHz Processor,Octa Core,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13,samsung
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,2.2 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,motorola
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",False,True,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,2.6 GHz Processor,Octa Core,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13,realme

In [ ]:
time 38